name: CI/CD Pipeline for Room Occupancy ML Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Build, Test, and Push Training Pipeline
  training_pipeline:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository to work with
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install dependencies for running the training script
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set lowercase repository name (to avoid Docker tag issues)
      - name: Set lowercase repository name
        id: repository_name
        run: echo "REPO_NAME=${{ github.repository }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV

      # Step 5: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Build and Push Training Image
      - name: Build and Push Training Image
        run: |
          docker build -f Docker/Dockerfile.training -t ghcr.io/${{ env.REPO_NAME }}/room-occupancy-training:latest .
          docker push ghcr.io/${{ env.REPO_NAME }}/room-occupancy-training:latest

  # Job 2: Build, Test, and Push API Endpoint Service
  api_endpoint:
    runs-on: ubuntu-latest
    needs: training_pipeline
    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set lowercase repository name (to avoid Docker tag issues)
      - name: Set lowercase repository name
        id: repository_name
        run: echo "REPO_NAME=${{ github.repository }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Build and Push API Image
      - name: Build and Push API Image
        run: |
          docker build -f Docker/Dockerfile.api -t ghcr.io/${{ env.REPO_NAME }}/room-occupancy-api:latest .
          docker push ghcr.io/${{ env.REPO_NAME }}/room-occupancy-api:latest
